export interface Artista {
  id: number;
  numeroArtista: string | null;
  nombreCompleto: string;
  esPropio: boolean;
  contacto: string | null;
  telefono: string | null;
  email: string | null;
  web: string | null;
  instagram: string | null;
  direccion: string | null;
  localidad: string | null;
  x: string | null;
  facebook: string | null;
  linkedin: string | null;
  fotoPath: string | null;
  logoPath: string | null;
  firmaPath: string | null;
  cuit: string | null;
  notas: string | null;
  fechaNacimiento: string | null;
  bio: string | null;
  bioEn: string | null;
  nombreArtistico: string | null;
  lugarNacimiento: string | null;
  lugarFallecimiento: string | null;
  lugarResidenciaTrabajo: string | null;
  nacionalidad: string | null;
  fechaFallecimiento: string | null;
  declaracionArtista: string | null;
  formacionAcademica: string | null;
  exposicionesIndividuales: string | null;
  exposicionesColectivas: string | null;
  premiosBecasReconocimientos: string | null;
  colecciones: string | null;
  publicacionesPrensa: string | null;
  fechaAltaSistema: string;
}

export interface NuevoArtista {
  numeroArtista?: string | null;
  nombreCompleto: string;
  esPropio: boolean;
  contacto?: string | null;
  telefono?: string | null;
  email?: string | null;
  web?: string | null;
  instagram?: string | null;
  direccion?: string | null;
  localidad?: string | null;
  x?: string | null;
  facebook?: string | null;
  linkedin?: string | null;
  fotoPath?: string | null;
  logoPath?: string | null;
  firmaPath?: string | null;
  cuit?: string | null;
  notas?: string | null;
  fechaNacimiento?: string | null;
  bio?: string | null;
  bioEn?: string | null;
  nombreArtistico?: string | null;
  lugarNacimiento?: string | null;
  lugarFallecimiento?: string | null;
  lugarResidenciaTrabajo?: string | null;
  nacionalidad?: string | null;
  fechaFallecimiento?: string | null;
  declaracionArtista?: string | null;
  formacionAcademica?: string | null;
  exposicionesIndividuales?: string | null;
  exposicionesColectivas?: string | null;
  premiosBecasReconocimientos?: string | null;
  colecciones?: string | null;
  publicacionesPrensa?: string | null;
}
